# Generated by Django 4.2.8 on 2023-12-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_vote'),
        ('gov_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='voting_app.user'),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='year_founded',
            field=models.DateField(),
        ),
    ]
