# Generated by Django 5.0 on 2023-12-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('secondname', models.CharField(max_length=15)),
                ('thirdname', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('identification', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
